name: Flutter Code Formatting

on:
  push:
    branches: [ feature-ci-cd ]
  pull_request:
    branches: [ feature-ci-cd ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.22.2

      - run: flutter pub get
        working-directory: ./dish_dash

      #- run: flutter format --set-exit-if-changed .
      #  working-directory: ./dish_dash