name: Flutter Code Deployment

on:
  push:
    branches: [ feature-ci-cd, develop ]
  pull_request:
    branches: [ feature-ci-cd, develop ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: '3.22.2'

      - run: flutter create -t app dish_dash_apk
      - run: cp -r ./dish_dash/lib ./dish_dash_apk/lib
      - run: cp ./dish_dash/pubspec.yaml ./dish_dash_apk/pubspec.yaml
      - run: cp -r ./dish_dash/assets ./dish_dash_apk/assets

      - run: flutter pub get
        working-directory: ./dish_dash_apk

      - run: flutter build apk --release
        working-directory: ./dish_dash_apk
      - uses: actions/upload-artifact@v2
        with:
          name: app-release.apk
          path: ./dish_dash_apk/build/app/outputs/flutter-apk/app-release.apk