name: Flutter Code Deployment

on:
  push:
    branches: [ feature-ci-cd ]
  pull_request:
    branches: [ feature-ci-cd ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: '3.22.2'

      - run: flutter pub get
        working-directory: ./dish_dash
      - run: flutter build web --release -t lib/main.dart
        working-directory: ./dish_dash

      - name: Deploy to GH Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web